"""empty message

Revision ID: 23243dd29ac4
Revises: 
Create Date: 2023-06-26 21:14:29.790754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23243dd29ac4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permisos')
    # ### end Alembic commands ###
